<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Update="SampleData\local-cluster-discovery-sample.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SampleData\remote-cluster-discovery-sample.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HealthChecks.UI.ServiceDiscovery.Kubernetes\HealthChecks.UI.ServiceDiscovery.Kubernetes.csproj" />
    <ProjectReference Include="..\..\src\HealthChecks.UI.Data\HealthChecks.UI.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

</Project>
